
# report: "report/workflow.rst"

# FILE = "in/Stardist/Test - Images/cell migration R1 - Position 58_XY1562686154_Z0_T00_C1-image76.tif"
# main_dir = "in/Stardist/Training - Images"
# files = glob_wildcards("/in/Stardist/Training - Images/")

files, = glob_wildcards("../in/Stardist/Test - Images/{file}.tif")

FILE_OUT = "out/out.zarr"
FILE_OUT_PNG = "out/out.png"
# FILE_OUT_QUALITY = "quality.txt"
FILE_OUT_QUALITY = "out/quality"


# All is a special rule that takes in the last output of the pipeline
rule all:
	input:
		expand("../in/Stardist/Test - Images/{file}/out.zarr", file=files)


rule scale_image_down_make_zarr:
	input:
		"../in/Stardist/Test - Images/{file}.tif"
	output:
		directory("../in/Stardist/Test - Images/{file}/out.zarr")
	# container:
	# 	"docker://continuumio/miniconda"
	conda:
		"environment.yml"
	shell:
		"python ../cool_script.py '{input}' '{output}'"
	# script:
	#     "cool_script.py {input} {output}"
